name: flutter_code
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  characters: ^1.4.0
  intl: ^0.20.2
  flutter_svg: ^2.1.0
  flutter_screenutil: ^5.9.3
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  hijri: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/svgs/

