name: Flutter CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Flutter (ensure Dart SDK 3.7+)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.5 # This includes Dart 3.7.0

      # Setup Java (needed for Android)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Disable analytics for CI (optional)
      - name: Disable Flutter analytics
        run: flutter config --no-analytics

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Analyze code
      - name: Analyze project
        run: flutter analyze

      # Run tests
      #- name: Run tests
      #  run: flutter test

      # Build Android APK (debug)
      - name: Build Android APK
        run: flutter build apk --debug
